export const products = [
  {
    id: 1,
    imgSrc: "/images/50-ML-1.png",
    imgHover: "/images/50-ML-1.png",
    title: "Black Opm Parfum Unisex Aroma Sweet Vanilla Coffee",
    price: 57000,
    oldPrice: 150000,
    isOnSale: false,
    hotSale: false,
    inStock: true,
  },
  {
    id: 2,
    imgSrc: "/images/50-ML-1.png",
    imgHover: "/images/50-ML-1.png",
    title: "Pinky Chiffony Parfum Wanita Aroma Vanilla Powdery",
    price: 57000,
    oldPrice: 150000,
    isOnSale: false,
    inStock: true,
  },
  {
    id: 3,
    imgSrc: "/images/50-ML-1.png",
    imgHover: "/images/50-ML-1.png",
    title: "Blooming Banquet Parfum Wanita Aroma Citrus Fresh",
    price: 57000,
    oldPrice: 150000,
    isOnSale: false,
    inStock: true,
  },
  {
    id: 4,
    imgSrc: "/images/50-ML-1.png",
    imgHover: "/images/50-ML-1.png",
    title: "Scandalusy Parfum Wanita Aroma Sweet Fruity",
    price: 57000,
    oldPrice: 150000,
    isOnSale: false,
    inStock: true,
  },
];
